### ISSUE TITLE
Gitlab CI/CD и k8s-handle

### ISSUE THREAD

**Issue by dekhtyarev** [rvadim/k8s-handle#3]
В Gitlab используем следующую конструкцию: 
```
staging:
  stage: deploy
  image: rvadim/k8s-handle:latest
  script:
    - export IMAGE_VERSION="master-${CI_COMMIT_SHA:0:8}"
    - k8s-handle deploy --section staging
```

Т.к. Gitlab, видимо, не переписывает существующий Entrypoint(`ENTRYPOINT ["/usr/local/bin/python", "/opt/k8s-handle/k8s-handle.py"]`) он пытается выполнить все команды в нём. 

И мы получаем ошибку: 
```
usage: k8s-handle.py [-h] {deploy,destroy} ...
k8s-handle.py: error: invalid choice: 'sh' (choose from 'deploy', 'destroy')
```

DoD: 
* При вызове команд(sh/bash) внутри k8s-handle они выполняются как задумано. 
* k8s-handle можно вызвать отдельной командой(не обязательно единственной)
