### ISSUE TITLE
Need deploy `kind: APIService` and `apiVersion: apiregistration.k8s.io/v1beta1`

### ISSUE THREAD

**Issue by dekhtyarev** [rvadim/k8s-handle#9]
Now, we have a error: 
```
ERROR:__main__:RuntimeError: Unknown kind "APIService" in generated file
ERROR: Job failed: exit code 1
```

Example for deploy:
```
---

apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  service:
    name: metrics-server
    namespace: kube-system
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
```
